//
// Created by Dave R. Smith on 1/10/23.
//

#ifndef UCS8_SPRING23_REVIEW_STUBS_AND_DRIVERS_LOGIC_H
#define UCS8_SPRING23_REVIEW_STUBS_AND_DRIVERS_LOGIC_H


class Logic
{

};


#endif //UCS8_SPRING23_REVIEW_STUBS_AND_DRIVERS_LOGIC_H
